{
  "protocol": "rest",
  "name": "analyticsdata",
  "discoveryVersion": "v1",
  "rootUrl": "https://analyticsdata.googleapis.com/",
  "mtlsRootUrl": "https://analyticsdata.mtls.googleapis.com/",
  "description": "Accesses report data in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning. ",
  "title": "Google Analytics Data API",
  "batchPath": "batch",
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics": {
          "description": "View and manage your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.chatbot.read": {
          "description": "Query Google Analytics data and insights conversationally"
        }
      }
    }
  },
  "resources": {
    "properties": {
      "methods": {
        "getMetadata": {
          "description": "Returns metadata for dimensions and metrics available in reporting methods. Used to explore the dimensions and metrics. In this method, a Google Analytics property identifier is specified in the request, and the metadata response includes Custom dimensions and metrics as well as Universal metadata. For example if a custom metric with parameter name `levels_unlocked` is registered to a property, the Metadata response will contain `customEvent:levels_unlocked`. Universal [...]",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "id": "analyticsdata.properties.getMetadata",
          "flatPath": "v1alpha/properties/{propertiesId}/metadata"
        },
        "runFunnelReport": {
          "flatPath": "v1alpha/properties/{propertiesId}:runFunnelReport",
          "path": "v1alpha/{+property}:runFunnelReport",
          "id": "analyticsdata.properties.runFunnelReport",
          "description": "Returns a customized funnel report of your Google Analytics event data. The data returned from the API is as a table with columns for the requested dimensions and metrics. Funnel exploration lets you visualize the steps your users take to complete a task and quickly see how well they are succeeding or failing at each step. For example, how do prospects become shoppers and then become buyers? How do one time buyers become repeat buyers? With this information, you can imp[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST"
        },
        "chat": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.chatbot.read"
          ],
          "id": "analyticsdata.properties.chat",
          "path": "v1alpha/{+property}:chat",
          "flatPath": "v1alpha/properties/{propertiesId}:chat",
          "httpMethod": "POST",
          "description": "Provides a chat interface for interacting with Google Analytics data through the API. This product uses AI and may display inaccurate info. Your chat activity may be used to improve the product and your use is subject to Google's [Terms](https://policies.google.com/terms), [AI Use Policy](https://policies.google.com/terms/generative-ai/use-policy), and [Privacy Policy](https://policies.google.com/privacy). [Learn more about Chat AI Privacy](https://support.google.com/he[...]"
        },
        "runReport": {
          "flatPath": "v1alpha/properties/{propertiesId}:runReport",
          "path": "v1alpha/{+property}:runReport",
          "description": "Returns a customized report of your Google Analytics event data. Reports contain statistics derived from data collected by the Google Analytics tracking code. The data returned from the API is as a table with columns for the requested dimensions and metrics. Metrics are individual measurements of user activity on your property, such as active users or event count. Dimensions break down metrics across some common criteria, such as country or event name.",
          "id": "analyticsdata.properties.runReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST"
        },
        "getPropertyQuotasSnapshot": {
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties/{propertiesId}/propertyQuotasSnapshot",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsdata.properties.getPropertyQuotasSnapshot",
          "description": "Get all property quotas organized by quota category for a given property. This will charge 1 property quota from the category with the most quota."
        }
      },
      "resources": {
        "reportTasks": {
          "methods": {
            "list": {
              "description": "Lists all report tasks for a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/reportTasks",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsdata.properties.reportTasks.list",
              "path": "v1alpha/{+parent}/reportTasks"
            },
            "query": {
              "flatPath": "v1alpha/properties/{propertiesId}/reportTasks/{reportTasksId}:query",
              "path": "v1alpha/{+name}:query",
              "id": "analyticsdata.properties.reportTasks.query",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Retrieves a report task's content. After requesting the `CreateReportTask`, you are able to retrieve the report content once the report is ACTIVE. This method will return an error if the report task's state is not `ACTIVE`. A query response will return the tabular row & column values of the report.",
              "httpMethod": "POST"
            },
            "get": {
              "description": "Gets report metadata about a specific report task. After creating a report task, use this method to check its processing state or inspect its report definition.",
              "id": "analyticsdata.properties.reportTasks.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/reportTasks/{reportTasksId}"
            },
            "create": {
              "id": "analyticsdata.properties.reportTasks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/reportTasks",
              "path": "v1alpha/{+parent}/reportTasks",
              "httpMethod": "POST",
              "description": "Initiates the creation of a report task. This method quickly returns a report task and initiates a long running asynchronous request to form a customized report of your Google Analytics event data. A report task will be retained and available for querying for 72 hours after it has been created. A report task created by one user can be listed and queried by all users who have access to the property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "recurringAudienceLists": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/recurringAudienceLists",
              "path": "v1alpha/{+parent}/recurringAudienceLists",
              "description": "Creates a recurring audience list. Recurring audience lists produces new audience lists each day. Audience lists are users in an audience at the time of the list's creation. A recurring audience list ensures that you have audience list based on the most recent data available for use each day. If you manually create audience list, you don't know when an audience list based on an additional day's data is available. This recurring audience list automates the creation o[...]",
              "httpMethod": "POST",
              "id": "analyticsdata.properties.recurringAudienceLists.create"
            },
            "list": {
              "id": "analyticsdata.properties.recurringAudienceLists.list",
              "description": "Lists all recurring audience lists for a property. This method can be used for you to find and reuse existing recurring audience lists rather than creating unnecessary new recurring audience lists. The same audience can have multiple recurring audience lists that represent different dimension combinations; for example, just the dimension `deviceId` or both the dimensions `deviceId` and `userId`. This method is introduced at alpha stability with the intention of gath[...]",
              "path": "v1alpha/{+parent}/recurringAudienceLists",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/recurringAudienceLists",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "get": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/recurringAudienceLists/{recurringAudienceListsId}",
              "id": "analyticsdata.properties.recurringAudienceLists.get",
              "description": "Gets configuration metadata about a specific recurring audience list. This method can be used to understand a recurring audience list's state after it has been created. For example, a recurring audience list resource will generate audience list instances for each day, and this method can be used to get the resource name of the most recent audience list instance. This method is introduced at alpha stability with the intention of gathering feedback on syntax and capab[...]",
              "httpMethod": "GET"
            }
          }
        },
        "audienceLists": {
          "methods": {
            "query": {
              "flatPath": "v1alpha/properties/{propertiesId}/audienceLists/{audienceListsId}:query",
              "description": "Retrieves an audience list of users. After creating an audience, the users are not immediately available for listing. First, a request to `CreateAudienceList` is necessary to create an audience list of users, and then second, this method is used to retrieve the users in the audience list. See [Creating an Audience List](https://developers.google.com/analytics/devguides/reporting/data/v1/audience-list-basics) for an introduction to Audience Lists with examples. Audie[...]",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsdata.properties.audienceLists.query",
              "path": "v1alpha/{+name}:query"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/audienceLists/{audienceListsId}",
              "httpMethod": "GET",
              "description": "Gets configuration metadata about a specific audience list. This method can be used to understand an audience list after it has been created. See [Creating an Audience List](https://developers.google.com/analytics/devguides/reporting/data/v1/audience-list-basics) for an introduction to Audience Lists with examples. This method is available at beta stability at [audienceExports.get](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/prope[...]",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsdata.properties.audienceLists.get"
            },
            "list": {
              "id": "analyticsdata.properties.audienceLists.list",
              "description": "Lists all audience lists for a property. This method can be used for you to find and reuse existing audience lists rather than creating unnecessary new audience lists. The same audience can have multiple audience lists that represent the list of users that were in an audience on different days. See [Creating an Audience List](https://developers.google.com/analytics/devguides/reporting/data/v1/audience-list-basics) for an introduction to Audience Lists with examples.[...]",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/audienceLists",
              "flatPath": "v1alpha/properties/{propertiesId}/audienceLists"
            },
            "create": {
              "id": "analyticsdata.properties.audienceLists.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/audienceLists",
              "description": "Creates an audience list for later retrieval. This method quickly returns the audience list's resource name and initiates a long running asynchronous request to form an audience list. To list the users in an audience list, first create the audience list through this method and then send the audience resource name to the `QueryAudienceList` method. See [Creating an Audience List](https://developers.google.com/analytics/devguides/reporting/data/v1/audience-list-basics[...]",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/audienceLists"
            }
          }
        }
      }
    }
  },
  "baseUrl": "https://analyticsdata.googleapis.com/",
  "basePath": "",
  "id": "analyticsdata:v1alpha",
  "servicePath": "",
  "canonicalName": "AnalyticsData",
  "kind": "discovery#restDescription",
  "revision": "20260909",
  "version": "v1alpha",
  "fullyEncodeReservedExpansion": true,
  "version_module": true,
  "documentationLink": "https://developers.google.com/analytics/devguides/reporting/data/v1/",
  "ownerName": "Google"
}
